export enum PropertyType {
	PETROL = 'PETROL',      // benzin
	DIESEL = 'DIESEL',      // dizel
	GAS = 'GAS',            // gaz
	HYBRID = 'HYBRID',      // gibrid
	ELECTRIC = 'ELECTRIC',  // elektro
}

export enum PropertyStatus {
	ACTIVE = 'ACTIVE',
	SOLD = 'SOLD',
	DELETE = 'DELETE',
}

export enum PropertyLocation {
	TASHKENT = 'TASHKENT',
	TASHKENT_REGION = 'TASHKENT_REGION',
	SAMARKAND = 'SAMARKAND',
	BUKHARA = 'BUKHARA',
	ANDIJAN = 'ANDIJAN',
	NAMANGAN = 'NAMANGAN',
	FERGANA = 'FERGANA',
	KHOREZM = 'KHOREZM',
	NAVOI = 'NAVOI',
	KASHKADARYA = 'KASHKADARYA',
	SURKHANDARYA = 'SURKHANDARYA',
	SYRDARYA = 'SYRDARYA',
	JIZZAKH = 'JIZZAKH',
	KARAKALPAKSTAN = 'KARAKALPAKSTAN',
}
